services:
  mongodb:
    image: mongo:7
    container_name: laravel_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db
    networks:
      - laravel

networks:
  laravel:
    external: true
volumes:
  mongodb_data: